### ISSUE TITLE
Package uses deprecated JSONField model fields

### ISSUE THREAD

**Issue by jacklinke** [Opus10/django-pgstats#3]
When installing django-pgstats, django's checks provide the following notes:

```
pgstats.IndexStats.stats: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
    HINT: Use django.db.models.JSONField instead.
pgstats.TableStats.stats: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
    HINT: Use django.db.models.JSONField instead.
```

Recommend updating file https://github.com/Opus10/django-pgstats/blob/master/pgstats/models.py to import and use `django.db.models.JSONField`

**Comment by asucrews** [comment]
i did a pull request for an update for jsonfields

https://github.com/Opus10/django-pgstats/pull/4

**Comment by githubcratos** [comment]
Can this be merged !!

**Comment by wesleykendall** [comment]
Version 1.0.8 addresses this. Apologies for the delay! pgtrigger and pghistory have been taking the majority of my time lately and I forgot about this one. Feel free to ping me directly for quick fixes next time, and I will do a better job about maintaining this library
